#!/bin/bash

source scripts/runsetup.sh

DJANKISERV_GUNICORN_TIMEOUT="${DJANKISERV_GUNICORN_TIMEOUT:-30}"
DJANKISERV_GUNICORN_WORKERS="${DJANKISERV_GUNICORN_WORKERS:-1}"
DJANKISERV_LISTEN_ADDRESS="${DJANKISERV_LISTEN_ADDRESS:-127.0.0.1}"
DJANKISERV_LISTEN_PORT="${DJANKISERV_LISTEN_PORT:-27701}"

gunicorn --timeout $DJANKISERV_GUNICORN_TIMEOUT --workers=$DJANKISERV_GUNICORN_WORKERS -b $DJANKISERV_LISTEN_ADDRESS:$DJANKISERV_LISTEN_PORT djankiserv_api.wsgi
