apiVersion: v1
kind: Service
metadata:
  name: {{ include "djankiserv.fullname" . }}-static
  labels:
    {{- include "djankiserv.static.labels" . | nindent 4 }}
spec:
  type: {{ .Values.static.service.type }}
  ports:
    - port: {{ .Values.static.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "djankiserv.static.selectorLabels" . | nindent 4 }}
